import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export const notoSans = Noto_Sans({
	subsets: ["latin"],
	weight: ["400", "600"],
	variable: "--font-noto-sans",
});

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={cn(
					"min-h-screen bg-background font-noto-sans antialiased flex justify-center items-center",
					notoSans.variable
				)}>
				{children}
			</body>
		</html>
	);
}
